// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHostToUserList(arg1) {
  return window['go']['app']['App']['AddHostToUserList'](arg1);
}

export function AddIgnoredVersion(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddIgnoredVersion'](arg1, arg2, arg3);
}

export function ApplyUpdate() {
  return window['go']['app']['App']['ApplyUpdate']();
}

export function AutoInstallZapret() {
  return window['go']['app']['App']['AutoInstallZapret']();
}

export function CancelAutoTest() {
  return window['go']['app']['App']['CancelAutoTest']();
}

export function CheckComponentUpdates() {
  return window['go']['app']['App']['CheckComponentUpdates']();
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CheckResource(arg1) {
  return window['go']['app']['App']['CheckResource'](arg1);
}

export function CheckWizardDone() {
  return window['go']['app']['App']['CheckWizardDone']();
}

export function CheckZPUIUpdate() {
  return window['go']['app']['App']['CheckZPUIUpdate']();
}

export function ClearCache(arg1) {
  return window['go']['app']['App']['ClearCache'](arg1);
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function DefaultStrategy() {
  return window['go']['app']['App']['DefaultStrategy']();
}

export function DeleteDevice(arg1) {
  return window['go']['app']['App']['DeleteDevice'](arg1);
}

export function DetectThirdPartyZapret() {
  return window['go']['app']['App']['DetectThirdPartyZapret']();
}

export function DisableAutostart() {
  return window['go']['app']['App']['DisableAutostart']();
}

export function EnableAutostart() {
  return window['go']['app']['App']['EnableAutostart']();
}

export function FrontendLogs(arg1) {
  return window['go']['app']['App']['FrontendLogs'](arg1);
}

export function GetActionLogs(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetActionLogs'](arg1, arg2, arg3);
}

export function GetArchiveLogs() {
  return window['go']['app']['App']['GetArchiveLogs']();
}

export function GetAutoUpdateStatus() {
  return window['go']['app']['App']['GetAutoUpdateStatus']();
}

export function GetAutostartStatus() {
  return window['go']['app']['App']['GetAutostartStatus']();
}

export function GetAvailabilityHistory(arg1, arg2) {
  return window['go']['app']['App']['GetAvailabilityHistory'](arg1, arg2);
}

export function GetBackups(arg1) {
  return window['go']['app']['App']['GetBackups'](arg1);
}

export function GetCachedResourcePercent() {
  return window['go']['app']['App']['GetCachedResourcePercent']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetDevice(arg1) {
  return window['go']['app']['App']['GetDevice'](arg1);
}

export function GetDeviceConnections(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetDeviceConnections'](arg1, arg2, arg3);
}

export function GetDevices() {
  return window['go']['app']['App']['GetDevices']();
}

export function GetErrorSnapshots() {
  return window['go']['app']['App']['GetErrorSnapshots']();
}

export function GetGameFilter() {
  return window['go']['app']['App']['GetGameFilter']();
}

export function GetIgnoredVersions() {
  return window['go']['app']['App']['GetIgnoredVersions']();
}

export function GetInstallLog() {
  return window['go']['app']['App']['GetInstallLog']();
}

export function GetIpsetStatus() {
  return window['go']['app']['App']['GetIpsetStatus']();
}

export function GetLists() {
  return window['go']['app']['App']['GetLists']();
}

export function GetLogDebug() {
  return window['go']['app']['App']['GetLogDebug']();
}

export function GetLogFiles() {
  return window['go']['app']['App']['GetLogFiles']();
}

export function GetLogs(arg1, arg2) {
  return window['go']['app']['App']['GetLogs'](arg1, arg2);
}

export function GetMonitorDevices() {
  return window['go']['app']['App']['GetMonitorDevices']();
}

export function GetNetworkInfo() {
  return window['go']['app']['App']['GetNetworkInfo']();
}

export function GetProxyConfig() {
  return window['go']['app']['App']['GetProxyConfig']();
}

export function GetProxyConnections() {
  return window['go']['app']['App']['GetProxyConnections']();
}

export function GetProxyQRCode() {
  return window['go']['app']['App']['GetProxyQRCode']();
}

export function GetProxyStatus() {
  return window['go']['app']['App']['GetProxyStatus']();
}

export function GetResourceStatus() {
  return window['go']['app']['App']['GetResourceStatus']();
}

export function GetServiceStatus() {
  return window['go']['app']['App']['GetServiceStatus']();
}

export function GetStatus() {
  return window['go']['app']['App']['GetStatus']();
}

export function GetStrategies() {
  return window['go']['app']['App']['GetStrategies']();
}

export function GetSystemResources() {
  return window['go']['app']['App']['GetSystemResources']();
}

export function GetSystemTheme() {
  return window['go']['app']['App']['GetSystemTheme']();
}

export function GetTraffic() {
  return window['go']['app']['App']['GetTraffic']();
}

export function GetTrafficSnapshots(arg1) {
  return window['go']['app']['App']['GetTrafficSnapshots'](arg1);
}

export function GetUpInfo() {
  return window['go']['app']['App']['GetUpInfo']();
}

export function GetVersions() {
  return window['go']['app']['App']['GetVersions']();
}

export function GetXboxDnsConfig() {
  return window['go']['app']['App']['GetXboxDnsConfig']();
}

export function HasLocalZapret() {
  return window['go']['app']['App']['HasLocalZapret']();
}

export function HasSystemZapretService() {
  return window['go']['app']['App']['HasSystemZapretService']();
}

export function HealthCheck() {
  return window['go']['app']['App']['HealthCheck']();
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function InstallOurZapret() {
  return window['go']['app']['App']['InstallOurZapret']();
}

export function InstallService(arg1) {
  return window['go']['app']['App']['InstallService'](arg1);
}

export function InstallServiceLogged(arg1) {
  return window['go']['app']['App']['InstallServiceLogged'](arg1);
}

export function InstallZapret(arg1) {
  return window['go']['app']['App']['InstallZapret'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['app']['App']['OpenExternal'](arg1);
}

export function PingDevice(arg1) {
  return window['go']['app']['App']['PingDevice'](arg1);
}

export function ProxyStart() {
  return window['go']['app']['App']['ProxyStart']();
}

export function ProxyStop() {
  return window['go']['app']['App']['ProxyStop']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function ReadArchiveLog(arg1) {
  return window['go']['app']['App']['ReadArchiveLog'](arg1);
}

export function ReadErrorSnapshot(arg1) {
  return window['go']['app']['App']['ReadErrorSnapshot'](arg1);
}

export function RemoveIgnoredVersion(arg1, arg2) {
  return window['go']['app']['App']['RemoveIgnoredVersion'](arg1, arg2);
}

export function RemoveService() {
  return window['go']['app']['App']['RemoveService']();
}

export function RemoveSystemZapretService() {
  return window['go']['app']['App']['RemoveSystemZapretService']();
}

export function RemoveThirdPartyZapret() {
  return window['go']['app']['App']['RemoveThirdPartyZapret']();
}

export function RestartApp() {
  return window['go']['app']['App']['RestartApp']();
}

export function RestoreFromBackup(arg1) {
  return window['go']['app']['App']['RestoreFromBackup'](arg1);
}

export function RunAutoSelectStream() {
  return window['go']['app']['App']['RunAutoSelectStream']();
}

export function RunAutoTestStream() {
  return window['go']['app']['App']['RunAutoTestStream']();
}

export function RunDiagnostics() {
  return window['go']['app']['App']['RunDiagnostics']();
}

export function RunUpdateStream() {
  return window['go']['app']['App']['RunUpdateStream']();
}

export function RunWizard() {
  return window['go']['app']['App']['RunWizard']();
}

export function SaveComponentStates() {
  return window['go']['app']['App']['SaveComponentStates']();
}

export function SaveList(arg1, arg2) {
  return window['go']['app']['App']['SaveList'](arg1, arg2);
}

export function SendTestNotification() {
  return window['go']['app']['App']['SendTestNotification']();
}

export function SetConfig(arg1) {
  return window['go']['app']['App']['SetConfig'](arg1);
}

export function SetGameFilter(arg1) {
  return window['go']['app']['App']['SetGameFilter'](arg1);
}

export function SetLogDebug(arg1, arg2) {
  return window['go']['app']['App']['SetLogDebug'](arg1, arg2);
}

export function SetProxyConfig(arg1) {
  return window['go']['app']['App']['SetProxyConfig'](arg1);
}

export function SetStrategy(arg1) {
  return window['go']['app']['App']['SetStrategy'](arg1);
}

export function SetXboxDnsConfig(arg1) {
  return window['go']['app']['App']['SetXboxDnsConfig'](arg1);
}

export function SetupApplyStrategy(arg1) {
  return window['go']['app']['App']['SetupApplyStrategy'](arg1);
}

export function SetupComplete() {
  return window['go']['app']['App']['SetupComplete']();
}

export function SetupConfigureDNS(arg1) {
  return window['go']['app']['App']['SetupConfigureDNS'](arg1);
}

export function SetupConfigureFilters(arg1) {
  return window['go']['app']['App']['SetupConfigureFilters'](arg1);
}

export function SetupConfigureProxy(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetupConfigureProxy'](arg1, arg2, arg3);
}

export function SetupControlCheck() {
  return window['go']['app']['App']['SetupControlCheck']();
}

export function SetupListStrategies(arg1) {
  return window['go']['app']['App']['SetupListStrategies'](arg1);
}

export function SetupSkip() {
  return window['go']['app']['App']['SetupSkip']();
}

export function SetupTestStrategy(arg1) {
  return window['go']['app']['App']['SetupTestStrategy'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function StartAutoTest() {
  return window['go']['app']['App']['StartAutoTest']();
}

export function StartOurZapret() {
  return window['go']['app']['App']['StartOurZapret']();
}

export function ToggleAutoUpdate(arg1) {
  return window['go']['app']['App']['ToggleAutoUpdate'](arg1);
}

export function ToggleIpset(arg1) {
  return window['go']['app']['App']['ToggleIpset'](arg1);
}

export function ToggleWindow() {
  return window['go']['app']['App']['ToggleWindow']();
}

export function ToggleXboxDns(arg1) {
  return window['go']['app']['App']['ToggleXboxDns'](arg1);
}

export function UpdateComponent(arg1) {
  return window['go']['app']['App']['UpdateComponent'](arg1);
}

export function UpdateHosts() {
  return window['go']['app']['App']['UpdateHosts']();
}

export function UpdateIpset() {
  return window['go']['app']['App']['UpdateIpset']();
}

export function VerifyZapretFiles() {
  return window['go']['app']['App']['VerifyZapretFiles']();
}

export function ZapretRestart() {
  return window['go']['app']['App']['ZapretRestart']();
}

export function ZapretStart() {
  return window['go']['app']['App']['ZapretStart']();
}

export function ZapretStop() {
  return window['go']['app']['App']['ZapretStop']();
}
