// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function AddHostToUserList(arg1:string):Promise<Record<string, any>>;

export function AddIgnoredVersion(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ApplyUpdate():Promise<Record<string, any>>;

export function AutoInstallZapret():Promise<Record<string, any>>;

export function CancelAutoTest():Promise<Record<string, any>>;

export function CheckComponentUpdates():Promise<Record<string, any>>;

export function CheckForUpdates():Promise<any>;

export function CheckResource(arg1:string):Promise<Record<string, any>>;

export function CheckWizardDone():Promise<boolean>;

export function CheckZPUIUpdate():Promise<Record<string, any>>;

export function ClearCache(arg1:string):Promise<Record<string, any>>;

export function ClearLogs():Promise<Record<string, any>>;

export function DefaultStrategy():Promise<Record<string, any>>;

export function DeleteDevice(arg1:string):Promise<Record<string, any>>;

export function DetectThirdPartyZapret():Promise<Record<string, any>>;

export function DisableAutostart():Promise<Record<string, any>>;

export function EnableAutostart():Promise<Record<string, any>>;

export function FrontendLogs(arg1:Array<any>):Promise<Record<string, any>>;

export function GetActionLogs(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function GetArchiveLogs():Promise<Record<string, any>>;

export function GetAutoUpdateStatus():Promise<Record<string, any>>;

export function GetAutostartStatus():Promise<Record<string, any>>;

export function GetAvailabilityHistory(arg1:number,arg2:string):Promise<Record<string, any>>;

export function GetBackups(arg1:string):Promise<Array<updater.BackupEntry>>;

export function GetCachedResourcePercent():Promise<number>;

export function GetConfig():Promise<Record<string, any>>;

export function GetDevice(arg1:string):Promise<Record<string, any>>;

export function GetDeviceConnections(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function GetDevices():Promise<Record<string, any>>;

export function GetErrorSnapshots():Promise<Record<string, any>>;

export function GetGameFilter():Promise<Record<string, any>>;

export function GetIgnoredVersions():Promise<Array<updater.IgnoredVersion>>;

export function GetInstallLog():Promise<Record<string, any>>;

export function GetIpsetStatus():Promise<Record<string, any>>;

export function GetLists():Promise<Record<string, any>>;

export function GetLogDebug():Promise<Record<string, any>>;

export function GetLogFiles():Promise<Record<string, any>>;

export function GetLogs(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetMonitorDevices():Promise<Record<string, any>>;

export function GetNetworkInfo():Promise<Record<string, any>>;

export function GetProxyConfig():Promise<any>;

export function GetProxyConnections():Promise<Record<string, any>>;

export function GetProxyQRCode():Promise<Record<string, any>>;

export function GetProxyStatus():Promise<Record<string, any>>;

export function GetResourceStatus():Promise<Record<string, any>>;

export function GetServiceStatus():Promise<any>;

export function GetStatus():Promise<Record<string, any>>;

export function GetStrategies():Promise<Record<string, any>>;

export function GetSystemResources():Promise<any>;

export function GetSystemTheme():Promise<string>;

export function GetTraffic():Promise<Record<string, any>>;

export function GetTrafficSnapshots(arg1:number):Promise<Record<string, any>>;

export function GetUpInfo():Promise<Record<string, any>>;

export function GetVersions():Promise<Record<string, any>>;

export function GetXboxDnsConfig():Promise<any>;

export function HasLocalZapret():Promise<boolean>;

export function HasSystemZapretService():Promise<boolean>;

export function HealthCheck():Promise<Record<string, any>>;

export function HideWindow():Promise<void>;

export function InstallOurZapret():Promise<Record<string, any>>;

export function InstallService(arg1:string):Promise<Record<string, any>>;

export function InstallServiceLogged(arg1:string):Promise<Record<string, any>>;

export function InstallZapret(arg1:string):Promise<Record<string, any>>;

export function OpenExternal(arg1:string):Promise<Record<string, any>>;

export function PingDevice(arg1:string):Promise<Record<string, any>>;

export function ProxyStart():Promise<Record<string, any>>;

export function ProxyStop():Promise<Record<string, any>>;

export function Quit():Promise<void>;

export function ReadArchiveLog(arg1:string):Promise<Record<string, any>>;

export function ReadErrorSnapshot(arg1:string):Promise<Record<string, any>>;

export function RemoveIgnoredVersion(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RemoveService():Promise<Record<string, any>>;

export function RemoveSystemZapretService():Promise<Record<string, any>>;

export function RemoveThirdPartyZapret():Promise<Record<string, any>>;

export function RestartApp():Promise<Record<string, any>>;

export function RestoreFromBackup(arg1:string):Promise<Record<string, any>>;

export function RunAutoSelectStream():Promise<void>;

export function RunAutoTestStream():Promise<void>;

export function RunDiagnostics():Promise<Record<string, any>>;

export function RunUpdateStream():Promise<void>;

export function RunWizard():Promise<Record<string, any>>;

export function SaveComponentStates():Promise<Record<string, any>>;

export function SaveList(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SendTestNotification():Promise<Record<string, any>>;

export function SetConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SetGameFilter(arg1:string):Promise<Record<string, any>>;

export function SetLogDebug(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function SetProxyConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SetStrategy(arg1:string):Promise<Record<string, any>>;

export function SetXboxDnsConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SetupApplyStrategy(arg1:string):Promise<Record<string, any>>;

export function SetupComplete():Promise<Record<string, any>>;

export function SetupConfigureDNS(arg1:boolean):Promise<Record<string, any>>;

export function SetupConfigureFilters(arg1:string):Promise<Record<string, any>>;

export function SetupConfigureProxy(arg1:boolean,arg2:number,arg3:string):Promise<Record<string, any>>;

export function SetupControlCheck():Promise<Record<string, any>>;

export function SetupListStrategies(arg1:string):Promise<Record<string, any>>;

export function SetupSkip():Promise<Record<string, any>>;

export function SetupTestStrategy(arg1:string):Promise<Record<string, any>>;

export function ShowWindow():Promise<void>;

export function StartAutoTest():Promise<Record<string, any>>;

export function StartOurZapret():Promise<Record<string, any>>;

export function ToggleAutoUpdate(arg1:boolean):Promise<Record<string, any>>;

export function ToggleIpset(arg1:string):Promise<Record<string, any>>;

export function ToggleWindow():Promise<void>;

export function ToggleXboxDns(arg1:boolean):Promise<Record<string, any>>;

export function UpdateComponent(arg1:string):Promise<Record<string, any>>;

export function UpdateHosts():Promise<Record<string, any>>;

export function UpdateIpset():Promise<Record<string, any>>;

export function VerifyZapretFiles():Promise<Record<string, any>>;

export function ZapretRestart():Promise<Record<string, any>>;

export function ZapretStart():Promise<Record<string, any>>;

export function ZapretStop():Promise<Record<string, any>>;
